loaders:
  - type: haystack_pydoc_tools.loaders.CustomPythonLoader
    search_path: [../src]
    modules: [
      "unify.components.embedders.document_embedder",
      "unify.components.embedders.text_embedder",
      "unify.components.generators.chat.chat_generator",
    ]
    ignore_when_discovered: ["__init__"]

processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref

renderer:
  type: haystack_pydoc_tools.renderers.ReadmeIntegrationRenderer
  excerpt: Unify integration for Haystack
  category_slug: integrations-api
  title: Unify
  slug: integrations-unify
  order: 160
  markdown:
    descriptive_class_title: false
    classdef_code_block: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: _readme_unify.md
